### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by purcell**
See https://github.com/milkypostman/melpa/pull/3269

### CODE REVIEW

**Comment by lujun9972** [comment]
sorry for my poor english and thank you for your fixing

**Comment by purcell** [comment]
Don't apologise! Thanks for sharing this code.

**Comment by lujun9972** [comment]
Hi,I wonder,when I add a package to melpa, is it a mandatory rule that a function should be defined like PACKAGE-FUNCTION?
Personally I prefer the PACKAGE/FUNCTION style for two reasons:
1. It is more clearly which part is the package name and which part is the function name
2. It is easier to  distinguish  a function from a variable

**Comment by purcell** [comment]
Yes, the official [Elisp coding conventions](https://www.gnu.org/s/emacs/manual/html_node/elisp/Coding-Conventions.html) say to use "-" (and "--" for private symbols). I also prefer the Clojure style with "/", but I still follow the elisp conventions because it's better for everyone if there's a consistent style across the community: community benefit is more important and arbitrary personal preferences IMO.

**Pull request merged**
